name: Chris Zhang
author: Chris Zhang
url: https://slcz.github.io
github_username: slcz
google_analytics_id: UA-73250606-1

markdown: kramdown
feed:
  path: blog.xml
exclude:
  - .gitignore
  - .travis.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
lsi: false
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /blog/:title/

navigation:
  - title: home
    link: /
  - title: blog
    link: /blog/
  - title: contact
    link: /contact/
